"""added email column

Revision ID: 85338c431b6d
Revises: 84cd2e3a2d7f
Create Date: 2018-09-04 18:51:59.372766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85338c431b6d'
down_revision = '84cd2e3a2d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['roles_id'], ['id'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'roles_id')
    # ### end Alembic commands ###
